"""Generate the Go workspace, side-effect imports, and effective plan."""

from __future__ import annotations

import json
import os
import re
from pathlib import Path
from typing import Dict, List

from .manifest import Integration, Manifest

INTERFACE_PATHS = (
    "clients/go_integration_interface",
    "clients/go_tool_interface",
)

IMPORTS_GEN_REL = "integrations/externalintegrations/imports_gen.go"
EFFECTIVE_PLAN_REL = ".generated/integrations.effective.json"
BUILD_TAGS_REL = ".generated/build_tags"
GOWORK_REL = "go.work"


class ResolveError(RuntimeError):
    pass


def _go_directive(backend_go_mod: Path) -> str:
    if backend_go_mod.exists():
        for line in backend_go_mod.read_text(encoding="utf-8").splitlines():
            match = re.match(r"^go\s+(\S+)", line.strip())
            if match:
                return match.group(1)
    return "1.26.0"


def build_plan(manifest: Manifest, profile: str) -> Dict:
    selected = manifest.profile_ids(profile)
    closure = manifest.closure(selected)

    tags: List[str] = []
    for integ_id in selected:
        for tag in manifest.integrations[integ_id].tags:
            if tag not in tags:
                tags.append(tag)
    if profile == "core-only" and "coreonly" not in tags:
        tags.append("coreonly")

    bootstrap = [manifest.integrations[i].bootstrap for i in selected]
    bootstrap = [b for b in bootstrap if b]

    modules = []
    for integ_id in closure:
        integ = manifest.integrations[integ_id]
        modules.append(
            {
                "id": integ.id,
                "module": integ.module,
                "import": integ.import_path,
                "path": integ.path,
                "selected": integ_id in set(selected),
            }
        )

    return {
        "profile": profile,
        "selected": selected,
        "closure": closure,
        "tags": tags,
        "bootstrap": bootstrap,
        "modules": modules,
    }


def _write_if_changed(path: Path, content: str) -> bool:
    if path.exists() and path.read_text(encoding="utf-8") == content:
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    return True


def write_go_work(manifest: Manifest, closure: List[str], log) -> Path:
    backend_dir = manifest.repo_root / "backend"
    go_version = _go_directive(backend_dir / "go.mod")

    uses: List[str] = ["./"]
    for rel in INTERFACE_PATHS:
        if (manifest.repo_root / rel / "go.mod").exists():
            uses.append(os.path.relpath(manifest.repo_root / rel, backend_dir).replace(os.sep, "/"))
        else:
            log(f"resolve: interface module missing, skipping workspace entry: {rel}")

    for integ_id in closure:
        integ = manifest.integrations[integ_id]
        path = manifest.path_for(integ)
        if not (path / "go.mod").exists():
            raise ResolveError(
                f"resolve: integration {integ_id!r} not materialized at {path}; run `sync` first"
            )
        uses.append(os.path.relpath(path, backend_dir).replace(os.sep, "/"))

    lines = [f"go {go_version}", "", "use ("]
    lines.extend(f"\t{u}" for u in uses)
    lines.append(")")
    content = "\n".join(lines) + "\n"

    gowork = backend_dir / GOWORK_REL
    changed = _write_if_changed(gowork, content)
    log(f"resolve: {'updated' if changed else 'unchanged'} {gowork.relative_to(manifest.repo_root)}")
    return gowork


def write_imports_gen(manifest: Manifest, selected: List[str], log) -> Path:
    imports = sorted({manifest.integrations[i].import_path for i in selected})
    lines = [
        "// Code generated by development/integrations/openchat_integrations. DO NOT EDIT.",
        "",
        "package externalintegrations",
        "",
    ]
    if imports:
        lines.append("import (")
        lines.extend(f'\t_ "{imp}"' for imp in imports)
        lines.append(")")
        lines.append("")

    path = manifest.repo_root / "backend" / IMPORTS_GEN_REL
    changed = _write_if_changed(path, "\n".join(lines))
    log(f"resolve: {'updated' if changed else 'unchanged'} {path.relative_to(manifest.repo_root)}")
    return path


def write_plan(manifest: Manifest, plan: Dict, log) -> Path:
    backend_dir = manifest.repo_root / "backend"
    plan_path = backend_dir / EFFECTIVE_PLAN_REL
    changed = _write_if_changed(plan_path, json.dumps(plan, indent=2) + "\n")
    log(f"resolve: {'updated' if changed else 'unchanged'} {plan_path.relative_to(manifest.repo_root)}")

    tags_path = backend_dir / BUILD_TAGS_REL
    _write_if_changed(tags_path, ",".join(plan["tags"]))
    return plan_path
